server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/open-delivery

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/open-delivery}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

service:
  mock: false